// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class DataMastersML
{
    /// <summary>
    /// model input class for DataMastersML.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"EventCategory")]
        public string EventCategory { get; set; }

        [ColumnName(@"CatalogueItemName")]
        public string CatalogueItemName { get; set; }

        [ColumnName(@"UnitCost")]
        public float UnitCost { get; set; }

        [ColumnName(@"UnitPrice")]
        public float UnitPrice { get; set; }

        [ColumnName(@"CatalogueType")]
        public string CatalogueType { get; set; }

        [ColumnName(@"ContactFirstName")]
        public string ContactFirstName { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for DataMastersML.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"EventCategory")]
        public float[] EventCategory { get; set; }

        [ColumnName(@"CatalogueItemName")]
        public uint CatalogueItemName { get; set; }

        [ColumnName(@"UnitCost")]
        public float UnitCost { get; set; }

        [ColumnName(@"UnitPrice")]
        public float UnitPrice { get; set; }

        [ColumnName(@"CatalogueType")]
        public float[] CatalogueType { get; set; }

        [ColumnName(@"ContactFirstName")]
        public float[] ContactFirstName { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public string PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float[] Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("DataMastersML.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
